<a href="https://colab.research.google.com/github/youngchul-sung/three-minutes-keras/blob/master/ex9_3_advanced_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2.x

import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Lambda, Input
from tensorflow.keras.models import Model
from tensorflow.keras import backend as K

def Lambda_with_lambda():
    x = Input((1,))
    y = Lambda(lambda x: x + 1)(x)
    m = Model(x, y)

    yp = m.predict_on_batch([1, 2, 3])
    print("np.array([1,2,3]) + 1:")
    print(yp)


def Lambda_function():
    def kproc(x):
        return x ** 2 + 2 * x + 1

    def kshape(input_shape):
        return input_shape

    x = Input((1,))
    y = Lambda(kproc, kshape)(x)
    m = Model(x, y)

    yp = m.predict_on_batch([1, 2, 3])
    print("np.array([1,2,3]) + 1:")
    print(yp)


def Backend_for_Lambda():
    def kproc_concat(x):    
        m = K.mean(x, axis=1, keepdims=True)
        d1 = K.abs(x - m)
        d2 = K.square(x - m)
        return K.concatenate([x, d1, d2], axis=1)

    def kshape_concat(input_shape):
        output_shape = list(input_shape)
        output_shape[1] *= 3
        return tuple(output_shape)

    x = Input((3,))
    y = Lambda(kproc_concat, kshape_concat)(x)
    m = Model(x, y)

    l = np.array([[1, 2, 3], [3, 4, 8]])
    yp = m.predict_on_batch(l)
    print(yp)


def TF_for_Lambda():
    def kproc_concat(x):    
        m = tf.math.reduce_mean(x, axis=1, keepdims=True)
        d1 = tf.abs(x - m)
        d2 = tf.square(x - m)
        return tf.concat([x, d1, d2], axis=1)

    def kshape_concat(input_shape):
        output_shape = list(input_shape)
        output_shape[1] *= 3
        return tuple(output_shape)

    x = Input((3,))
    y = Lambda(kproc_concat, kshape_concat)(x)
    m = Model(x, y)

    l = np.array([[1, 2, 3], [3, 4, 8]])
    yp = m.predict_on_batch(l)
    print(yp)


def main():
    print('Lambda with lambda')
    Lambda_with_lambda()

    print('Lambda function')
    Lambda_function()

    print('Backend for Lambda')
    Backend_for_Lambda()

    print('TF for Lambda')
    TF_for_Lambda()

if __name__ == '__main__':
    main()

TensorFlow 2.x selected.
Lambda with lambda
np.array([1,2,3]) + 1:
tf.Tensor(
[[2.]
 [3.]
 [4.]], shape=(3, 1), dtype=float32)
Lambda function
np.array([1,2,3]) + 1:
tf.Tensor(
[[ 4.]
 [ 9.]
 [16.]], shape=(3, 1), dtype=float32)
Backend for Lambda
tf.Tensor(
[[1. 2. 3. 1. 0. 1. 1. 0. 1.]
 [3. 4. 8. 2. 1. 3. 4. 1. 9.]], shape=(2, 9), dtype=float32)
TF for Lambda
tf.Tensor(
[[1. 2. 3. 1. 0. 1. 1. 0. 1.]
 [3. 4. 8. 2. 1. 3. 4. 1. 9.]], shape=(2, 9), dtype=float32)
